WAIT 1000
WRITE [(q4,43)(n7,49)(j7,31)]
WRITE [(i6,87)(l1,60)(e4,29)(g1,85)(r0,6)]
WAIT 1000
READ [g1]
DELETE [g1,q4,r0,n7]
SHOW
DELETE [l1,e4,j7,i6]
WRITE [(o5,27)(v2,62)(v4,69)(s5,29)]
WRITE [(n0,62)(o6,57)]
DELETE [v4]
READ [o6]
WRITE [(e0,50)(k0,26)]
DELETE [e0]
WRITE [(x3,94)(i7,5)]
WAIT 2000
DELETE [x3,k0,o6]
WRITE [(l0,33)]
DELETE [s5]
READ [o5]
DELETE [n0,v2,i7]
READ [l0]
WRITE [(b3,39)(s2,75)(y8,25)(y2,34)(g5,62)]
BACKUP
READ [s2]
WRITE [(e1,82)(s5,95)(i4,31)(o0,52)(f2,74)]
BACKUP
WRITE [(q4,47)(q8,26)(w2,38)]
WRITE [(r1,94)(r2,5)(s6,15)(r7,54)]
WRITE [(k2,51)(s8,44)(h6,84)(f4,98)(a5,6)]
DELETE [y8,l0,o5,s6,e1]
WRITE [(r4,14)(v1,30)(n9,68)]
READ [v1]
WRITE [(t8,33)]
