WRITE [(n4,73)]
DELETE [n4]
WRITE [(j9,54)]
WRITE [(x4,97)(a4,73)(x6,5)(x1,89)]
DELETE [j9]
WAIT 2000
READ [x6]
WRITE [(b8,28)(r3,74)(y5,78)(k9,25)]
WAIT 1000
WRITE [(v2,96)(v4,49)(m3,19)]
BACKUP
WRITE [(q0,33)(n6,90)(d5,94)(t4,73)]
READ [q0]
SHOW
READ [y5]
WRITE [(m2,71)]
SHOW
DELETE [x1,m2,a4,x6,x4]
DELETE [k9,y5]
DELETE [d5,v2,v4,n6]
WAIT 1000
WAIT 2000
DELETE [q0]
WRITE [(c5,67)(j3,83)(s4,99)(y0,82)(x5,23)]
READ [y0]
DELETE [y0,c5,t4,s4]
WRITE [(r0,4)]
READ [r0]
DELETE [r0,x5,j3,m3,r3]
WRITE [(k9,47)(f1,6)(m7,96)]
READ [f1]
READ [f1]
READ [f1]
READ [m7]
SHOW
READ [b8]
WRITE [(g2,66)(y2,9)]
WRITE [(f3,16)(d4,31)(r5,33)(u6,49)]
BACKUP
SHOW
WRITE [(u3,82)(n0,5)(c8,51)(v5,11)(u2,85)]
READ [k9]
BACKUP
DELETE [v5,m7]
WRITE [(m1,48)(h4,32)(j0,100)(z2,65)(k8,45)]
WAIT 3000
WRITE [(n9,15)(r1,42)(k5,66)]
BACKUP
READ [f1]
WRITE [(p6,3)(s3,72)(f9,1)]
WAIT 2000
WRITE [(k6,73)(m9,17)(o7,83)(x0,68)]
WRITE [(i0,17)(f8,18)(j2,12)(z6,52)(a9,50)]
READ [s3]
WRITE [(a6,8)(w0,44)(w0,54)(d6,7)]
WRITE [(e9,83)(o0,89)(i3,75)]
DELETE [n9]
WRITE [(w4,42)(q2,44)(s9,62)(a3,75)(q9,62)]
WRITE [(p3,35)(j5,18)(n2,82)(w7,64)(k3,31)]
WRITE [(j9,0)(o5,41)(s6,39)(v5,89)]
WRITE [(l3,55)(r6,5)]
READ [o0]
WRITE [(h6,28)]
WRITE [(v4,49)]
READ [r1]
WRITE [(n1,6)(g5,28)]
WAIT 3000
WRITE [(t0,9)(a2,40)(d5,66)]
WRITE [(s7,13)(g8,45)(j3,0)(m6,51)]
WRITE [(x1,59)]
WRITE [(h7,99)(i9,45)(v0,30)(p5,69)(l8,55)]
SHOW
READ [f1]
READ [w0]
READ [q9]
DELETE [r1,k8,s9]
DELETE [n1,j5,m9,x1]
READ [w7]
WRITE [(e4,11)]
BACKUP
READ [p3]
WRITE [(y3,39)(r0,82)(o1,4)(t3,79)]
DELETE [f3,h4,o0,f8]
WRITE [(y5,39)]
WRITE [(p9,84)(h5,90)(l4,3)(h0,93)]
