WRITE [(j2,50)]
WRITE [(v0,93)(o3,8)(u5,11)(b6,42)(g8,7)]
DELETE [o3,b6]
WRITE [(x9,37)(c0,2)(o8,54)(g6,99)]
WRITE [(i8,28)]
WRITE [(e1,65)(n3,0)(w9,0)]
WRITE [(q6,54)(u0,52)(w7,37)]
DELETE [n3]
DELETE [c0,w9,e1,i8,g6]
SHOW
BACKUP
WAIT 1000
READ [u5]
DELETE [w7,v0,q6]
WAIT 2000
WRITE [(n6,75)(b6,82)(a1,40)(g9,50)(s4,68)]
WRITE [(v4,77)(x0,36)(o0,17)(w2,33)]
READ [o8]
WRITE [(i9,40)(b1,100)(r6,53)(z6,13)]
WRITE [(p6,75)(e4,0)(p8,88)(n3,61)]
READ [o0]
WRITE [(d3,7)(v3,26)(s3,23)(f5,86)(q8,39)]
WRITE [(s2,29)(k7,57)(w1,38)(n7,87)(p7,97)]
WRITE [(e7,95)(j9,11)(j0,9)(k5,25)]
DELETE [p7,j0,i9,u0,k7]
SHOW
READ [a1]
BACKUP
DELETE [n6,x9,w2,d3,k5]
WRITE [(c9,3)(i4,62)(x6,5)]
WRITE [(c7,72)]
READ [z6]
WRITE [(f1,46)(g1,68)]
WRITE [(q1,21)(j0,100)(v2,56)]
READ [v3]
WRITE [(y5,19)(d1,74)(q5,45)(j8,64)]
DELETE [q1,b1]
WRITE [(d3,19)(n4,32)(h5,65)(y7,18)]
DELETE [e7]
WRITE [(h0,2)(m9,70)]
READ [s4]
WRITE [(o1,87)]
WAIT 3000
SHOW
WRITE [(y4,51)(e0,81)]
SHOW
READ [n3]
BACKUP
WRITE [(e6,45)(s7,5)(g4,14)]
WRITE [(y8,98)(c0,73)(f7,74)(y1,66)(i8,17)]
BACKUP
READ [y1]
DELETE [e4,o0,c7,c0,n3]
SHOW
WRITE [(h9,90)(q1,61)]
WAIT 2000
BACKUP
WRITE [(y2,30)(f3,28)]
DELETE [g9,p6,v2]
DELETE [h9,z6]
READ [c9]
READ [f7]
DELETE [g1,y8,y4]
WRITE [(i0,70)(v2,80)(w3,86)(m2,34)]
WRITE [(f8,41)(d4,24)(q7,51)]
